//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TravelManagementSite.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    
    public partial class Train
    {

        public int id { get; set; }
         [DisplayName("Name")]
        public string name { get; set; }

         [DisplayName("Source")]
        public string source { get; set; }

         [DisplayName("Destination")]
        public string destination { get; set; }
        public System.DateTime date { get; set; }
    }
}
